// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scawpozfubunltbzkbvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjYXdwb3pmdWJ1bmx0YnprYnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDY4NjUsImV4cCI6MjA1ODkyMjg2NX0.G6wCywkUBbkFPB16EQpBoJoH-dJdfeGC5DAsd5tF4Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);